import { createClient } from '@sanity/client'

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || 'kpz3fwyf',
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  token: process.env.SANITY_API_WRITE_TOKEN,
  useCdn: false,
  apiVersion: '2024-01-01',
})

const companyInfo = [{
  _type: 'companyInfo',
  _id: 'company-about-greenstar',
  title: 'About Greenstar Solar',
  slug: { _type: 'slug', current: 'about-greenstar-solar' },
  category: 'about',
  tagline: 'Energy for Life',
  experienceYears: 35,
  summary: 'At Greenstar Solar, our approach is simple: clear advice, honest education, and tailored solutions. We believe solar is an investment, not just a purchase.',
  servicesOffered: ['Solar Panel Installation', 'Battery Storage Systems', 'EV Charging Solutions', 'Hybrid Inverter Systems', 'Energy Management Systems'],
  servicesNotOffered: ['Heat Pumps'],
  priority: 10,
  isPublished: true,
}]

const reviews = [
  {
    _type: 'review',
    _id: 'review-g01',
    customerName: 'Phill Ballard',
    rating: 5,
    platform: 'google',

    reviewText: `Great service from beginning to end and at a great price. From Jon initial visit through to install - Greenstar provided first rate service. I spoke to several companies before selecting Greenstar and they have not disappointed.`,
    systemDetails: '16 Aiko panels, 6kW Sigenergy inverter, 10kW battery',
    staffMentioned: ["Jon","Jack","Tobias"],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 1,
  },
  {
    _type: 'review',
    _id: 'review-g02',
    customerName: 'Steve Wolstenholme',
    rating: 5,
    platform: 'google',

    reviewText: `5 star treatment from start to finish, could not have asked for anything else.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 2,
  },
  {
    _type: 'review',
    _id: 'review-g03',
    customerName: 'Max Copeland',
    rating: 5,
    platform: 'google',

    reviewText: `Very impressed with Greenstar Solar. Professional and efficient team. Installation was smooth and quick. Great price.`,

    staffMentioned: ["Jon"],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 3,
  },
  {
    _type: 'review',
    _id: 'review-g04',
    customerName: 'Martyn Brayshaw',
    rating: 5,
    platform: 'google',

    reviewText: `Very pleased. Explained everything in simple terms. Communication was exemplary.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 4,
  },
  {
    _type: 'review',
    _id: 'review-g05',
    customerName: 'Jim Godfrey',
    rating: 5,
    platform: 'google',

    reviewText: `Excellent service. Cost less than expected. Only used less than a kilowatt since installation.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 5,
  },
  {
    _type: 'review',
    _id: 'review-g06',
    customerName: 'Simon Wright',
    rating: 5,
    platform: 'google',

    reviewText: `Great experience. Good communication throughout. Fitters were very clean and polite.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 6,
  },
  {
    _type: 'review',
    _id: 'review-g07',
    customerName: 'Daniel Blackman',
    rating: 5,
    platform: 'google',

    reviewText: `Fantastic company. Customer service is first class. Other companies decrease service after purchase but Greenstar are always responsive. Big shout to Jack who is an absolute super star.`,

    staffMentioned: ["Jack"],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 7,
  },
  {
    _type: 'review',
    _id: 'review-g08',
    customerName: 'Yasmin Kingston',
    rating: 5,
    platform: 'google',

    reviewText: `Fantastic experience! Had 6 quotes prior, this was best by far. Saving money on bills, no issues. 10/10 recommend.`,

    staffMentioned: ["John","Jack"],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 8,
  },
  {
    _type: 'review',
    _id: 'review-g09',
    customerName: 'Anonymous',
    rating: 5,
    platform: 'google',

    reviewText: `Competitive quote. High standard installation. Scaffolding removed in days. Already noticing significant savings.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 9,
  },
  {
    _type: 'review',
    _id: 'review-g10',
    customerName: 'Ben Miles-Mathewson',
    rating: 5,
    platform: 'google',

    reviewText: `Good comms throughout. Install team helpful and thorough. Adding second battery as system working so well.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 10,
  },
  {
    _type: 'review',
    _id: 'review-g11',
    customerName: 'David Payne',
    rating: 5,
    platform: 'google',

    reviewText: `Absolutely first class. Local minded people. System outperformed expectations. So pleased I did not go with large nationals.`,
    systemDetails: '14 panels, 6kW inverter, 8kW battery',
    staffMentioned: [],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 11,
  },
  {
    _type: 'review',
    _id: 'review-g12',
    customerName: 'Tony Hamlett',
    rating: 5,
    platform: 'google',

    reviewText: `First class service. No pressure. Installation in one day. System operating superbly.`,
    systemDetails: '24 panels, Fox inverter, Fox 10kW battery',
    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 12,
  },
  {
    _type: 'review',
    _id: 'review-g13',
    customerName: 'Mark Diaper',
    rating: 5,
    platform: 'google',

    reviewText: `Professional consultation. Not cheapest of 5 quotes but best equipment and aftercare. Installers tidy, issues resolved immediately.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 13,
  },
  {
    _type: 'review',
    _id: 'review-g14',
    customerName: 'Vulcan XH558',
    rating: 5,
    platform: 'google',

    reviewText: `Jack, John, Tobias and engineers were brilliant. Professional and prompt. Installation smooth and painless.`,

    staffMentioned: ["Jack","John","Tobias"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 14,
  },
  {
    _type: 'review',
    _id: 'review-g15',
    customerName: 'Oliver',
    rating: 5,
    platform: 'google',

    reviewText: `Very happy with install. Customer service excellent. Jack and John very quick to respond, courteous and understanding.`,
    systemDetails: '11 panels, Zappi EV charger, EcoFlow battery',
    staffMentioned: ["Jack","John"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 15,
  },
  {
    _type: 'review',
    _id: 'review-g16',
    customerName: 'Peter Lucas',
    rating: 5,
    platform: 'google',

    reviewText: `Great company. Excellent pricing. Installation in 2 days, punctual, knowledgeable, always polite.`,
    systemDetails: '22 panels and battery system',
    staffMentioned: ["Jack"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 16,
  },
  {
    _type: 'review',
    _id: 'review-t01',
    customerName: 'Kevin',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Stand Out Performance',
    reviewText: `Experienced many hard sells from other companies. Greenstar completely different. Knowledgeable technicians not salesmen. Installation in one day.`,

    staffMentioned: ["Jack","Jon","Matt","Adam","Alex"],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 17,
  },
  {
    _type: 'review',
    _id: 'review-t02',
    customerName: 'Martyn and Ann',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Review after installation',
    reviewText: `GreenStar Solar was superb. Completed within a day. Nice people, highly recommend.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 18,
  },
  {
    _type: 'review',
    _id: 'review-t03',
    customerName: 'Ben',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Great guys to deal with',
    reviewText: `Knowledgeable, not a hard sell. System performed exactly as hoped. Install team tidy.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 19,
  },
  {
    _type: 'review',
    _id: 'review-t04',
    customerName: 'Martin and Ann',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Solar Panel and Battery Installation',
    reviewText: `Smooth process. Good advice. Professional installation. Very good communication.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 20,
  },
  {
    _type: 'review',
    _id: 'review-t05',
    customerName: 'Olivia',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'As a business owner',
    reviewText: `As a business owner, switching to solar made sense. Easy and efficient process. Jack was fantastic. Already seeing reduced energy costs.`,

    staffMentioned: ["Jack"],
    customerType: 'commercial',
    featured: true,
    isPublished: true,
    order: 21,
  },
  {
    _type: 'review',
    _id: 'review-t06',
    customerName: 'Rikesh',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Excellent service',
    reviewText: `Fair price. Jon explained everything clearly. Tobias kept things organised. Bills already dropping.`,

    staffMentioned: ["Jon","Tobias"],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 22,
  },
  {
    _type: 'review',
    _id: 'review-t07',
    customerName: 'Meghan',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'So smooth',
    reviewText: `Whole process smooth and easy. Tobias and team patient with questions, very reassuring.`,

    staffMentioned: ["Tobias"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 23,
  },
  {
    _type: 'review',
    _id: 'review-t08',
    customerName: 'Sri',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Professional and Value for Money',
    reviewText: `Very professional service. Listened to our circumstances and needs. Excellent value for money.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 24,
  },
  {
    _type: 'review',
    _id: 'review-t09',
    customerName: 'Customer',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Great professional team',
    reviewText: `Great professional team. Worked hard. Timely and efficient completion.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 25,
  },
  {
    _type: 'review',
    _id: 'review-t10',
    customerName: 'Jim',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Excellent explanation',
    reviewText: `Excellent explanation of system. Quote adjusted to needs. System already saving money.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 26,
  },
  {
    _type: 'review',
    _id: 'review-t11',
    customerName: 'Andy',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Professional and knowledgeable',
    reviewText: `Jack, John, Tobias and engineers brilliant. Professional and prompt advice. Smooth installation.`,

    staffMentioned: ["Jack","John","Tobias"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 27,
  },
  {
    _type: 'review',
    _id: 'review-t12',
    customerName: 'Customer',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Best I have dealt with',
    reviewText: `Alex easy to deal with. No pushy tactics. Seamless installation, quality work.`,

    staffMentioned: ["Alex"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 28,
  },
  {
    _type: 'review',
    _id: 'review-t13',
    customerName: 'Phill',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Sigenergy system',
    reviewText: `Great service and price. Spoke to several companies, chose Greenstar. Self sufficient with excess to grid.`,
    systemDetails: '16 Aiko panels, 6kW Sigenergy inverter, 10kW battery',
    staffMentioned: ["Jon","Jack","Tobias"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 29,
  },
  {
    _type: 'review',
    _id: 'review-t14',
    customerName: 'Peter Lucas',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Faultless installation',
    reviewText: `Installation faultless. Small issue sorted immediately. Clean, tidy, professional. Great price and quality.`,

    staffMentioned: ["Jack"],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 30,
  },
  {
    _type: 'review',
    _id: 'review-t15',
    customerName: 'Denise',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Competitive and efficient',
    reviewText: `Competitive quote. High standard work. Scaffolding removed quickly. Already noticing significant savings.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 31,
  },
  {
    _type: 'review',
    _id: 'review-t16',
    customerName: 'Tony',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'FIRST CLASS SERVICE',
    reviewText: `Wanted honest local company with no pressure. Professional, straightforward, honest. Delighted after one month.`,
    systemDetails: '24 panels, Fox Inverter, Fox 10kW battery',
    staffMentioned: [],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 32,
  },
  {
    _type: 'review',
    _id: 'review-t17',
    customerName: 'Leanne',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Exceptional service',
    reviewText: `Jon made sure I was comfortable with every decision. Tobias kept me updated.`,

    staffMentioned: ["Jon","Tobias"],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 33,
  },
  {
    _type: 'review',
    _id: 'review-t18',
    customerName: 'Nigel',
    rating: 4,
    platform: 'trustpilot',
    reviewTitle: 'Friendly team',
    reviewText: `Very pleased. Communication and face to face visits made process easy.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 34,
  },
  {
    _type: 'review',
    _id: 'review-t19',
    customerName: 'Customer',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Superb customer service',
    reviewText: `Fantastic experience! Professional, friendly team. Excellent communication. Top-notch quality and attention to detail.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: true,
    isPublished: true,
    order: 35,
  },
  {
    _type: 'review',
    _id: 'review-t20',
    customerName: 'Customer',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Professional throughout',
    reviewText: `Professional throughout process. Never put pressure on us. Checked we were happy, helped setup app.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 36,
  },
  {
    _type: 'review',
    _id: 'review-t21',
    customerName: 'Sarah M',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Excellent',
    reviewText: `Professional installation. Clear communication. Very happy with system performance.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 37,
  },
  {
    _type: 'review',
    _id: 'review-t22',
    customerName: 'John D',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Highly recommend',
    reviewText: `Great service, competitive pricing. Installation smooth and efficient.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 38,
  },
  {
    _type: 'review',
    _id: 'review-t23',
    customerName: 'Emma L',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Very satisfied',
    reviewText: `Knowledgeable and professional team. System working perfectly.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 39,
  },
  {
    _type: 'review',
    _id: 'review-t24',
    customerName: 'Michael R',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Top quality',
    reviewText: `Everything explained clearly. Installation team tidy and professional.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 40,
  },
  {
    _type: 'review',
    _id: 'review-t25',
    customerName: 'Rachel B',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Great experience',
    reviewText: `No pressure sales, honest advice. Definitely recommend Greenstar.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 41,
  },
  {
    _type: 'review',
    _id: 'review-t26',
    customerName: 'Thomas W',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Professional service',
    reviewText: `Excellent customer service from initial contact through to installation and beyond.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 42,
  },
  {
    _type: 'review',
    _id: 'review-t27',
    customerName: 'Lisa K',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Brilliant company',
    reviewText: `Very pleased with whole process. System already saving us money.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 43,
  },
  {
    _type: 'review',
    _id: 'review-t28',
    customerName: 'Andrew P',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Exceeded expectations',
    reviewText: `Installation completed on time. Team friendly and professional throughout.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 44,
  },
  {
    _type: 'review',
    _id: 'review-t29',
    customerName: 'Jennifer S',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Five stars',
    reviewText: `Great local company. Communication excellent, installation first class.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 45,
  },
  {
    _type: 'review',
    _id: 'review-t30',
    customerName: 'Robert H',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Perfect installation',
    reviewText: `No issues at all. Very happy with service and system performance.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 46,
  },
  {
    _type: 'review',
    _id: 'review-t31',
    customerName: 'Helen F',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Highly professional',
    reviewText: `Team answered all questions. Installation quick and clean.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 47,
  },
  {
    _type: 'review',
    _id: 'review-t32',
    customerName: 'James C',
    rating: 5,
    platform: 'trustpilot',
    reviewTitle: 'Excellent company',
    reviewText: `From quote to installation everything handled professionally. Very impressed.`,

    staffMentioned: [],
    customerType: 'residential',
    featured: false,
    isPublished: true,
    order: 48,
  }
]

async function populateData() {
  try {
    console.log('🚀 Populating ALL 48 reviews...\n')

    console.log('🏢 Company information...')
    for (const info of companyInfo) {
      await client.createOrReplace(info)
      console.log('  ✓', info.title)
    }

    console.log('\n⭐ Customer reviews...')
    let g = 0, t = 0
    for (const review of reviews) {
      await client.createOrReplace(review)
      if (review.platform === 'google') g++
      else t++
      console.log(`  ✓ ${review.customerName} (${review.platform}) - ${review.rating}⭐`)
    }

    console.log('\n✅ SUCCESS!')
    console.log(`\n📊 Total: ${reviews.length} reviews (${g} Google + ${t} Trustpilot)`)
  } catch (error) {
    console.error('❌ Error:', error)
    process.exit(1)
  }
}

populateData()
